<?php
/**
 * TL_ROOT/system/modules/pgnviewer/languages/de/default.php 
 * 
 * Contao extension: pgnviewer 1.3.1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2012-2016 Wilfried Krebbers 
 * License   : LGPL 
 * Author    : Wilfried Krebbers (wik) 
 * Translator: Wilfried Krebbers (wik) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['schach'] = "Schach-Elemente";
$GLOBALS['TL_LANG']['CTE']['pgnviewer']['0'] = "PGNViewer";
$GLOBALS['TL_LANG']['CTE']['pgnviewer']['1'] = "Eine PGN-Datei einbinden und mit Brett darstellen";
 
?>
