<?php
/**
 * TL_ROOT/system/modules/pgnviewer/languages/de/tl_content.php 
 * 
 * Contao extension: pgnviewer 1.3.1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2012-2016 Wilfried Krebbers 
 * License   : LGPL 
 * Author    : Wilfried Krebbers (wik) 
 * Translator: Wilfried Krebbers (wik) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['modul_config'] = "Element Konfiguration";
$GLOBALS['TL_LANG']['tl_content']['download_legend'] = "Download Einstellungen";
$GLOBALS['TL_LANG']['tl_content']['pgn_file']['0'] = "PGN-Datei";
$GLOBALS['TL_LANG']['tl_content']['pgn_file']['1'] = "Bitte wählen Sie eine PGN-Datei aus.";
$GLOBALS['TL_LANG']['tl_content']['pgn_piecesize']['0'] = "Figurengröße auswählen";
$GLOBALS['TL_LANG']['tl_content']['pgn_piecesize']['1'] = "Bitte wählen Sie die Größe der Figuren aus (in px).";
$GLOBALS['TL_LANG']['tl_content']['pgn_pieceset']['0'] = "Figurensatz auswählen";
$GLOBALS['TL_LANG']['tl_content']['pgn_pieceset']['1'] = "Bitte wählen Sie den Figurensatz aus.";
$GLOBALS['TL_LANG']['tl_content']['pgn_pause']['0'] = "Pause zwischen den Zügen";
$GLOBALS['TL_LANG']['tl_content']['pgn_pause']['1'] = "Die Länge der Zeit in Millisekunden, die zwischen den Zügen bei Autoplaying-Spielen gewartet wird.";
$GLOBALS['TL_LANG']['tl_content']['pgn_moveformat']['0'] = "Züge formatiert ausgeben";
$GLOBALS['TL_LANG']['tl_content']['pgn_moveformat']['1'] = "Züge formatiert ausgeben.";
$GLOBALS['TL_LANG']['tl_content']['pgn_boardfirst']['0'] = "Brett vor Notation ausgeben";
$GLOBALS['TL_LANG']['tl_content']['pgn_boardfirst']['1'] = "Es wird erst das Spielbrett, dann die Notation ausgegeben.";
$GLOBALS['TL_LANG']['tl_content']['pgn_backlink']['0'] = "Backlink zu Chess Tempo anzeigen";
$GLOBALS['TL_LANG']['tl_content']['pgn_backlink']['1'] = "Der ChessTempo PGN-Viewer ist unter einer Creative Commons-Lizenz lizensiert. Sie dürfen den Viewer kostenlos auf Ihrer nicht-kommerziellen Webseite verwenden, unter der Bedingung, dass Sie einen sichtbaren Link zu http://chesstempo.com auf dieser Seite platzieren.";
$GLOBALS['TL_LANG']['tl_content']['pgn_coordinates']['0'] = "Koordinaten anzeigen";
$GLOBALS['TL_LANG']['tl_content']['pgn_coordinates']['1'] = "Zeigt die Koordinaten an der Seite des Brettes an.";
$GLOBALS['TL_LANG']['tl_content']['pgn_autoscroll']['0'] = "Autoscroll aktivieren";
$GLOBALS['TL_LANG']['tl_content']['pgn_autoscroll']['1'] = "Die Partienotation soll automatisch mitscrollen.";
$GLOBALS['TL_LANG']['tl_content']['pgn_sound']['0'] = "Sound aktivieren";
$GLOBALS['TL_LANG']['tl_content']['pgn_sound']['1'] = "Die Spielzüge werden akustisch begleitet.";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat']['0'] = "Partiedaten anzeigen";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat']['1'] = "Partiedaten auswählen die angezeigt werden sollen.";
$GLOBALS['TL_LANG']['tl_content']['pgn_download']['0'] = "Download der PGN-Datei";
$GLOBALS['TL_LANG']['tl_content']['pgn_download']['1'] = "Download der PGN-Datei ermöglichen. ACHTUNG! In den Einstellungen unter 'Erlaubte Download-Dateitypen' den Dateityp 'pgn' eintragen.";
$GLOBALS['TL_LANG']['tl_content']['pgn_titleText']['0'] = "Link-Title";
$GLOBALS['TL_LANG']['tl_content']['pgn_titleText']['1'] = "Der Link-Titel wird als title-Attribut im HTML-Markup eingefügt";
$GLOBALS['TL_LANG']['tl_content']['pgn_linkTitle']['0'] = "Link-Text";
$GLOBALS['TL_LANG']['tl_content']['pgn_linkTitle']['1'] = "Der Link-Text wird anstelle der Link-Adresse angezeigt.";
$GLOBALS['TL_LANG']['tl_content']['pgn_notationsize']['0'] = "Höhe des Notationsfenster";
$GLOBALS['TL_LANG']['tl_content']['pgn_notationsize']['1'] = "Beschränkt das Notationsfesters auf die hier festgelegte max. Höhe (in Pixel). Geben Sie 0 ein um die Beschränkung aufzuheben (sinnvoll wenn Sie dies per CSS selbst gestalten).";
$GLOBALS['TL_LANG']['tl_content']['pgn_pieceset_option']['merida'] = "Merida";
$GLOBALS['TL_LANG']['tl_content']['pgn_pieceset_option']['leipzig'] = "Leipzig";
$GLOBALS['TL_LANG']['tl_content']['pgn_pieceset_option']['maya'] = "Maya";
$GLOBALS['TL_LANG']['tl_content']['pgn_pieceset_option']['condal'] = "Condal";
$GLOBALS['TL_LANG']['tl_content']['pgn_pieceset_option']['case'] = "Case";
$GLOBALS['TL_LANG']['tl_content']['pgn_pieceset_option']['kingdom'] = "Kingdom";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['event'] = "Turnier";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['site'] = "Ort";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['date'] = "Datum";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['round'] = "Runde";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['white'] = "Weiß";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['black'] = "Schwarz";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['result'] = "Ergebnis";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['eco'] = "ECO";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['elo_w'] = "ELO Weiß";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['elo_b'] = "ELO Schwarz";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['plycount'] = "Anzahl der Halbzüge";
$GLOBALS['TL_LANG']['tl_content']['pgn_gamestat_option']['annotator'] = "Kommentator";
 
?>
