<?php
/**
 * TL_ROOT/system/modules/pgnviewer/languages/de/tl_settings.php 
 * 
 * Contao extension: pgnviewer 1.3.1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2012-2016 Wilfried Krebbers 
 * License   : LGPL 
 * Author    : Wilfried Krebbers (wik) 
 * Translator: Wilfried Krebbers (wik) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer'] = "PGNViewer";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_notationlang']['1'] = "Hier können Sie die Notationssprache ändern.";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_notationlang']['0'] = "Notationssprache auswählen";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_notationlang_option']['en'] = "Englisch (Standard) - KQRBNP";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_notationlang_option']['fig_l'] = "Symbole hell - ♔♕♖♗♘♙";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_notationlang_option']['fig_d'] = "Symbole dunkel - ♚♛♜♝♞♟";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_notationlang_option']['de'] = "Deutsch - KDTLSB";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_notationlang_option']['pl'] = "Polnisch - KHWGSP";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_notationlang_option']['cz'] = "Tschechisch - KDVSJP";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_notationlang_option']['nl'] = "Niederländisch - KDTLPO";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_notationlang_option']['fr'] = "Französisch - RDTFCP";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_notationlang_option']['es'] = "Spanisch - RDTACP";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_sound']['1'] = "Ist dies deaktiviert, kann im PGNViewer die Sound-Option nicht angewählt werden und es werden grundsätzlich keine Spielgeräusche mehr abgespielt.";
$GLOBALS['TL_LANG']['tl_settings']['pgnviewer_sound']['0'] = "'Sound aktivieren' freischalten";
 
?>
